### PR TITLE
Camera Assembly

### PR DESCRIPTION
**Pull request by cianmawhinney**
PR for #11 

Initially tried using ESP-IDF, but it seems like projects created with this framework require >10x the code of the arduino framework, plus there are far fewer tutorials to look at

Camera board will take a picture every 5s and POST it to a web server in the body of the request.

Also added a small web server to test the file uploads. This is only intended to be temporary and can be deleted once the main web server is written.

Servo controller - does a GET request every few seconds to fetch what angle it should turn the servo to. For simplicity, I assume this number is the only thing in the body of the request.

### CODE REVIEW

**Comment by tedski999** [comment]
As explained on Discord, in order to accommodate using the Arduino framework while providing secure updates using OTA and secure boot, we need to transition from PlatformIO to the ESP-IDF build tool and then provide Arduino as an ESP-IDF component. This will let us use any library built on the Arduino API while giving us full access to ESP-IDF functionality. I'm working on that right now, but it will necessitate some boilerplate code changes. The application logic should all remain the same.

**Comment by cianmawhinney** [comment]
Just for future reference: when programming the ESP32-DevKitC you need to press the boot button to allow the flash to be written to.

Still have to add the HTTP queries to the code for fetching the servo position.

**Review by tedski999 — APPROVED** [review]
Logic looks sound to me, great work.

**Comment by cianmawhinney** [comment]
Thanks! I'll merge this now and refactor the code into the new format at the weekend

**Pull request merged**
